### ISSUE TITLE
Version 4 Compatible

### ISSUE THREAD

**Issue by elliotcondon** [stormuk/bbPress-ACF-field#1]
Hi @adampope 

Great work on this field, I'm sure a lot of developers will be stoked to use it on their projects.

Can I ask if you would wrap this field up into a v3 and v4 compatible plugin? I've got a field type template here which you can use to rapidly create the plugin!

https://github.com/elliotcondon/acf-field-type-template

Let me know if you have the time to create it. Then I can add the field type to the add-ons page on the ACF site!

**Comment by lgladdy** [comment]
Hey Elliot - we're updating our plugins today.

In doing so, we noticed a bug that if your folder name is alphabetically after "adv", the plugin is loaded after ACF's core plugin and isn't included on version 3.

I've sent a pull request to the template (https://github.com/elliotcondon/acf-field-type-template/pull/6) that fixes it by setting the priority of the plugin's init action (5) to higher than ACF's init default (which is 10)

**Comment by elliotcondon** [comment]
Thanks @lgladdy 

I'll merge it in!
